name: get tag name

on:
  push:
    tags:
      - "*"

jobs:
  # 環境変数を使うパターン
  env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: echo tag name
        run: |
          echo "${TAG_NAME}"
          echo "${{ env.TAG_NAME }}"

  # output を使うパターン
  output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get tag name
        id: get-tag-name
        run: echo "tag-name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: echo tag name
        run: echo ${{ steps.get-tag-name.outputs.tag-name }}
